2023-01-03 16:10:25,658 ERROR: Exception on /api/users [GET] [in C:\Users\wolfe\microblog\.venv\Lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\wolfe\microblog\.venv\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wolfe\microblog\.venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wolfe\microblog\.venv\Lib\site-packages\flask\app.py", line 1842, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wolfe\microblog\.venv\Lib\site-packages\flask\app.py", line 2134, in make_response
    raise TypeError(
TypeError: The view function for 'api.get_users' did not return a valid response. The function either returned None or ended without a return statement.
2023-01-03 16:26:07,734 ERROR: Exception on /api/users/1/followers [GET] [in C:\Users\wolfe\microblog\.venv\Lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\wolfe\microblog\.venv\Lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wolfe\microblog\.venv\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wolfe\microblog\.venv\Lib\site-packages\flask\app.py", line 1842, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wolfe\microblog\.venv\Lib\site-packages\flask\app.py", line 2134, in make_response
    raise TypeError(
TypeError: The view function for 'api.get_followers' did not return a valid response. The function either returned None or ended without a return statement.
2023-01-03 16:59:16,585 INFO: Microblog startup [in C:\Users\wolfe\microblog\app\__init__.py:77]
2023-01-03 16:59:33,972 INFO: Microblog startup [in C:\Users\wolfe\microblog\app\__init__.py:77]
